package com.smartpillbox.app.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "alarms")
data class AlarmEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val medicineId: Int,
    val medicineName: String = "",
    val dosage: String = "",
    val hour: Int,
    val minute: Int,
    val label: String = "",
    val isEnabled: Boolean = true,
    val isAutoGenerated: Boolean = true,
    val snoozeMinutes: Int = 5,
    val reminderNote: String = "",
    val createdAt: Long = System.currentTimeMillis()
)