package com.smartpillbox.app.util

import com.smartpillbox.app.data.local.AlarmEntity
import com.smartpillbox.app.data.local.MedicineEntity

object ScheduleGenerator {

    data class TimeSlot(val hour: Int, val minute: Int, val label: String)

    private val MORNING = TimeSlot(8, 0, "Morning")
    private val AFTERNOON = TimeSlot(14, 0, "Afternoon")
    private val EVENING = TimeSlot(20, 0, "Evening")
    private val BEDTIME = TimeSlot(22, 30, "Bedtime")

    fun generateAlarms(medicine: MedicineEntity): List<AlarmEntity> {
        val freq = medicine.frequency.lowercase()

        if (freq.contains("sos") || freq.contains("as needed") || freq.contains("prn")) {
            return emptyList()
        }

        val slots = determineTimeSlots(freq)
        return slots.map { slot ->
            AlarmEntity(
                medicineId = medicine.id,
                medicineName = medicine.name,
                dosage = medicine.dosage,
                hour = slot.hour,
                minute = slot.minute,
                label = slot.label,
                isEnabled = true,
                isAutoGenerated = true
            )
        }
    }

    // CHANGED: was private, now public so ScanResultsActivity can call it
    fun determineTimeSlots(freq: String): List<TimeSlot> {
        return when {
            freq.contains("three times") || freq.contains("tds") ||
                    freq.contains("tid") || freq.contains("1-1-1") ->
                listOf(MORNING, AFTERNOON, EVENING)

            freq.contains("twice") || freq.contains("bd") ||
                    freq.contains("bid") || freq.contains("1-0-1") ->
                listOf(MORNING, EVENING)

            freq.contains("four times") || freq.contains("qid") ->
                listOf(
                    TimeSlot(8, 0, "Morning"),
                    TimeSlot(12, 0, "Noon"),
                    TimeSlot(16, 0, "Afternoon"),
                    TimeSlot(20, 0, "Evening")
                )

            freq.contains("every 4 hour") || freq.contains("q4h") ->
                listOf(
                    TimeSlot(8, 0, "Morning"),
                    TimeSlot(12, 0, "Noon"),
                    TimeSlot(16, 0, "Afternoon"),
                    TimeSlot(20, 0, "Evening")
                )

            freq.contains("every 6 hour") || freq.contains("q6h") ->
                listOf(MORNING, AFTERNOON, EVENING)

            freq.contains("every 8 hour") || freq.contains("q8h") ->
                listOf(MORNING, EVENING)

            freq.contains("bedtime") || freq.contains("hs") ||
                    freq.contains("night") || freq.contains("0-0-1") ->
                listOf(BEDTIME)

            freq.contains("morning") || freq.contains("1-0-0") ->
                listOf(MORNING)

            else -> listOf(MORNING) // Default: once daily in the morning
        }
    }
}